name: salve
version: 0.0.0

category: Distribution
description: Salve provides semantic version numbers and constraints.
extra-source-files: CHANGELOG.markdown
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Semantic version numbers and constraints.

dependencies: base >=4.8.2 && <4.11
ghc-options: -Wall

library:
  source-dirs: library

tests:
  doctest:
    dependencies:
      - doctest >=0.10.1 && <0.14
      - microlens >=0.3.5 && <0.5
    main: doctest.hs
    source-dirs: tests

benchmarks:
  benchmark:
    dependencies:
      - criterion >=1.1.0 && <1.3
      - deepseq >=1.4.1 && <1.5
      - salve
    main: benchmark.hs
    source-dirs: benchmarks
